export const ON_CHANGE_INPUT = 'ON_CHANGE_INPUT';

export const ON_CHANGE_RADIO = 'ON_CHANGE_RADIO';

export const HANDLE_CREATE_CATEGORY_SUBMIT = 'HANDLE_CREATE_CATEGORY_SUBMIT';

export const HANDLE_EDIT_CATEGORY = 'HANDLE_EDIT_CATEGORY';
export const HANDLE_EDIT_CATEGORY_SUCCESS = 'HANDLE_EDIT_CATEGORY_SUCCESS';
export const HANDLE_EDIT_CATEGORY_FAILURE = 'HANDLE_EDIT_CATEGORY_SUCCESS';

export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE';

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILURE = 'GET_CATEGORY_BY_ID_FAILURE';

export const HANDLE_DELETE_CATEGORY = 'HANDLE_DELETE_CATEGORY';
export const HANDLE_DELETE_CATEGORY_SUCCESS = 'HANDLE_DELETE_CATEGORY_SUCCESS';
export const HANDLE_DELETE_CATEGORY_FAILURE = 'HANDLE_DELETE_CATEGORY_FAILURE';

export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL';

export const ON_CHANGE_SEARCH = 'ON_CHANGE_SEARCH';

export const RESET_SEARCH_INPUT = 'RESET_SEARCH_INPUT';

export const CHANGE_CATE_PAGE_NUMBERS = 'CHANGE_CATE_PAGE_NUMBERS';

export const CHANGE_PAGE_NUMBER_FILTER = 'CHANGE_PAGE_NUMBER_FILTER';

export const RESET_CATEGORY_META = 'RESET_CATEGORY_META';

export const RESET_ADD_CATE_FORM = 'RESET_ADD_CATE_FORM';

export const UPDATE_ERRORS = 'UPDATE_ERRORS';

export const RESET_ERRORS = 'RESET_ERRORS';

export const catePageNumberOptions = [10, 20, 30, 40, 50];

export const categoryMetaInitital = {
  searchKey: '',
  perPage: 10,
  currentPage: 1,
}

export const categoryInitial = {
  category_name: '',
  category_parent: 'volvo',
  group: '',
  authority_user: [],
}
